dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - OpenZeppelin/openzeppelin-contracts@4.4.0
  

compiler:
  solc:
    remappings:
      - '@chainlink=C:/Users/dave_/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@0.2.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0'


dotenv: .env
wallets:
  
  private_key_player1: ${PRIVATE_KEY_1}
  private_key_player2: ${PRIVATE_KEY_2}
  private_key_player3: ${PRIVATE_KEY_3}
  private_key_player4: ${PRIVATE_KEY_4}
  private_key_player5: ${PRIVATE_KEY_5}


api_keys:
  # Reference the API key env
  etherscan: ${ETHERSCAN_TOKEN}
# For vrf_coordinators see
# https://docs.chain.link/docs/vrf-contracts/#configurations
networks:
  default: development
  development:
    keyhash: '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    vrf_coordinator: '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    subscriptionid: 5292
    verify: False
  kovan:
    verify: True 
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
  rinkeby:
    verify: True
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    subscriptionid: 5292
  mainnet-fork-dev:
    verify: False
  mainnet-fork-infura:
    verify: False
  mainnet-fork:
    verify: False
    mykey: 'mainnet-fork-key'
  mainnet:
    verify: True
  ganache-local:
    verify: False

